name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: git-actions-cluste # TODO: update to cluster name
  GKE_ZONE: us-central1 # TODO: update to cluster zone
  DEPLOYMENT_NAME: node-deployment # TODO: update to deployment name
  REPOSITORY: fernandoojeda7/git-actions # TODO: update to Artifact Registry docker repository
  IMAGE: gcr.io/thermal-loop-414917/node-app

jobs:
  setup-build-publish-deploy:
    name: Configurar, Compilar, Publicar y Desplegar
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - id: auth
        name: Autenticar en Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # - name: Configuración de Docker en Google Cloud
      #   run: |-
      #     gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      # Obtener las credenciales de GKE para poder desplegar en el clúster
      - name: Configurar credenciales de GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Autenticación en Docker hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Obtener SHA del commit
        run: |
          GIT_COMMIT_SHA=$(git rev-parse HEAD)
          echo "SHA del commit actual: $GIT_COMMIT_SHA"
        shell: bash

      # Construir la imagen de Docker
      - name: Compilar
        run: |-
          docker build \
            --tag "fernandoojeda7/git-actions:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Publicar la imagen de Docker en Docker Hub
      - name: Publicar
        run: |-
          docker push "fernandoojeda7/git-actions:$GITHUB_SHA"

      # Desplegar la imagen de Docker en el clúster de GKE
      - name: Desplegar
        run: |-
          kubectl apply -f app.yaml
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
